app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as'=>'guest.index','uses'=>'GlobalController@homeIndex']);
Route::get('portfolio', ['as'=>'guest.portfolio.index','uses'=>'PortfolioController@portfolioIndex']);
Route::get('portfolio/{id}/{slug}', ['as'=>'guest.portfolio.show','uses'=>'PortfolioController@singleIndex']);
Route::get('contact', ['as'=>'guest.contact.index', 'uses'=>'ContactController@index']);
Route::post('contact', ['as'=>'guest.contact.store', 'uses'=>'ContactController@store']);
Route::get('about', ['as'=>'guest.about.index', 'uses'=>'GlobalController@about']);

Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role:admin']], function() {
	Route::get('dashboard', ['as'=>'admin.dashboard', 'uses'=>'Admin\GlobalController@dashboard']);
	Route::resource('user', 'Admin\UserController');
	Route::get('service/all', ['as'=>'admin.service.showAction', 'uses'=>'Admin\ServiceController@showAction']);
	Route::resource('teacher', 'Admin\TeacherController');
	Route::resource('service', 'Admin\ServiceController', ['except'=>['show','create']]);
	Route::resource('saids', 'Admin\SaidController');
	Route::resource('label', 'Admin\LabelController');
	Route::resource('portfolio', 'Admin\PortfolioController');


	Route::group(['prefix'=>'options'], function() {
		Route::get('user',['as'=>'admin.options.user', 'uses'=>'OptionsController@accountIndex']);
		Route::patch('user/password',['as'=>'admin.options.passSave', 'uses'=>'OptionsController@passSave']);
		Route::patch('user/info',['as'=>'admin.options.userInfo', 'uses'=>'OptionsController@userInfo']);

		// Socials
		Route::get('social', ['as'=>'admin.options.socials', 'uses'=>'OptionsController@socialIndex']);
		Route::patch('social/update', ['as'=>'admin.options.socialSave', 'uses'=>'OptionsController@socialSave']);

		// Site Options
		Route::get('site', ['as'=>'admin.options.site', 'uses'=>'OptionsController@siteIndex']);
		Route::patch('site/update', ['as'=>'admin.options.siteSave', 'uses'=>'OptionsController@siteSave']);
		Route::patch('site/verification', ['as'=>'admin.options.verification', 'uses'=>'OptionsController@verification']);

		// Page Options
		Route::get('page', ['as'=>'admin.options.page', 'uses'=>'OptionsController@pageIndex']);
		Route::patch('page/update', ['as'=>'admin.options.pageSave', 'uses'=>'OptionsController@pageSave']);
	});

});
Route::group(['prefix'=>'member', 'middleware'=>['auth', 'role:member']], function() {
  Route::resource('label', 'Admin\LabelController');
	Route::resource('portfolio', 'Admin\PortfolioController');
  Route::resource('label', 'Admin\LabelController');
});

resources/views/partials/_labelLists.blade.php
<?php $i = 1+($labels->perPage() * 0)+$labels->currentPage()-1; ?>
@foreach ($labels as $label)
<tr>
    <td>{{ $i++ }}</td>
    <td>{{ $label->label }}</td>
    <td></td>
    <td>
        <a href="#modal-edit" data-toggle="modal" data-url="{{ route('admin.label.edit', ['id'=>$label->id]) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
        <button data-delete="delete" data-url="{{ route('admin.label.destroy', ['id'=>$label->id]) }}" class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash"></i></button>
    </td>
</tr>
@endforeach
<script src="{{ asset('admin/plugins/jQuery/jquery-2.2.3.min.js') }}"></script>
<script>
    $('button[data-delete="delete"]').on('click', function(e) {
            e.preventDefault;

            konf = confirm('Apakah anda yakin  mau menghapus data ini?');
            if(!konf) {
                return false;
            }
            
            data = $(this).attr('data-url');

            $.ajaxSetup({
                headers: {'X-CSRF-Token' : $('meta[name="csrf-token"]').attr('content') }
            });

            $.ajax({
                url : data,
                type : 'delete',
                success: function(data) {
                    obj = sukses.find('.isi').append(data.message);
                    sukses.slideDown();
                    $('#faker').load('label/create');
                }
            });
        });
</script>

resources/views/partials/_modalFaker.blade.php
{!! Form::model($data,['url'=>route('admin.saids.update',['id'=>$data->id]), 'class'=>'form-horizontal', 'id'=>'form-edit', 'method'=>'patch']) !!}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">Edit Data</h4>
</div>
<div class="modal-body">
    <div class="form-group">
        <label class="control-label col-sm-2">Nama</label>
        <div class="col-sm-10">
            {!! Form::text('name', null, ['class'=>'form-control']) !!}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2">Sebagai</label>
        <div class="col-sm-10">
            {!! Form::text('passion', null, ['class'=>'form-control']) !!}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2">Content</label>
        <div class="col-sm-10">
            {!! Form::textarea('content', null, ['class'=>'form-control']) !!}
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save changes</button>
</div>
{!! Form::close() !!} 

resources/views/partials/_modalLabel.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">Edit Label : {{ $label->label }}</h4>
</div>
<div class="modal-body">
    <form action="" method="POST" class="form-horizontal">
		<div class="form-group">
			<label class="col-sm-2">Label</label>
			<div class="col-sm-10">
				<input type="hidden" name="_token" value="{{ csrf_token() }}" style="display: none;">
				<input type="text" name="label" id="fakerrrrr" class="form-control" value="{{ $label->label }}">
			</div>
		</div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary" id="modal-save">Save changes</button>
</div>
<script src="{{ asset('admin/plugins/jQuery/jquery-2.2.3.min.js') }}"></script>
<script>
	$(document).ready(function() {
		$('#modal-save').click(function(e) {
			e.preventDefault;
			info = $('#info');
			sukses = $('#success');

			$.ajaxSetup({
				headers : {'X-CSRF-Token' : $('input[name="_token"]').val() }
			});

			$.ajax({
				url : 'label/{{ $label->id }}',
				type : 'patch',
				data : {
					'label' : $('#fakerrrrr').val()
				},
				success : function(data) {
					if(!data.success) {
						obj = info.find('ul').empty();
                        $.each(data.message, function(index, message) {
                            obj.append('<li>'+message+'</li>');
                        });
                        info.slideDown();
					} else {
						sukses.find('.isi').text(' ');
                        obj = sukses.find('.isi').append(data.message);
                        sukses.slideDown();

                        $('#faker').load('label/create');
					}
				}
			});
		});
	});
</script>

resources/views/partials/_modalTeacher.blade.php
{!! Form::model($teacher, ['url'=>route('admin.teacher.update', ['id'=>$teacher->id]),'method'=>'patch', 'files'=>true]) !!}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">Edit Guru : {{ $teacher->nama }}</h4>
</div>
<div class="modal-body">
    <div class="table-responsive">
        <table class="table table-striped">
            <tbody>
                <tr>
                    <th>Nama</th>
                    <td>{!! Form::text('nama', null, ['class'=>'form-control']) !!}</td>
                </tr>
                <tr>
                    <th>Pelajaran</th>
                    <td>{!! Form::text('mapel', null, ['class'=>'form-control']) !!}</td>
                </tr>
                <tr>
                    <th>Foto</th>
                    <td>{!! Form::file('foto', ['class'=>'form-control']) !!}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" id="add-guru" class="btn btn-primary">Save</button>
</div>
{!! Form::close() !!}

resources/views/partials/_modalUsers.blade.php
{!! Form::model($user, ['url'=>route('admin.user.update', ['id'=>$user->id]), 'method'=>'patch']) !!}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">Edit User : {{ $user->name }}</h4>
</div>
<div class="modal-body">
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <tbody>
                <tr>
                    <th>Name</th>
                    <td>{!! Form::text('name', null, ['class'=>'form-control']) !!}</td>
                </tr>
                <tr>
                    <th>Username</th>
                    <td>{!! Form::text('username', null, ['class'=>'form-control']) !!}</td>
                </tr>
                <tr>
                    <th>Password</th>
                    <td>{!! Form::password('password', ['class'=>'form-control']) !!}</td>
                </tr>
                <tr>
                    <th>Role</th>
                    <td>{!! Form::select('role', ['1'=>'Admin', '2'=>'Member'], $user->role_id, ['class'=>'form-control']) !!}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-primary">Save</button>
    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
</div>
{!! Form::close() !!}

resources/views/partials/_resultFaker.blade.php
<?php $i = 1+($saids->perPage() * 0)+$saids->currentPage()-1; ?>
@foreach ($saids as $said)
<tr>
    <td>{{ $i++ }}</td>
    <td>{{ $said->name }}</td>
    <td>{{ $said->passion }}</td>
    <td>{{ str_limit($said->content, 50) }}</td>
    <td><a data-toggle="modal" href='#modal-edit' data-url="{{ route('admin.saids.edit',['id'=>$said->id]) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
    {!! Form::open(['url'=>route('admin.saids.destroy', ['id'=>$said->id]), 'method'=>'delete', 'style'=>'display:inline-block !important','class'=>'form-delete']) !!}
    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
    {!! Form::close() !!}
    </td>
</tr>
@endforeach

resources/views/partials/_serviceLists.blade.php
<?php $i = 1+($services->perPage() * 0)+$services->currentPage()-1; ?>
@foreach ($services as $service)
<tr>
    <td>{{ $i++ }}</td>
    <td>{{ $service->title }}</td>
    <td>{{ $service->desc }}</td>
    <td><i class="fa fa-2x fa-{{ $service->icon }}"></i></td>
    <td>
        <a href="{{ route('admin.service.edit', ['id'=>$service->id]) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
        {!! Form::open(['url'=>route('admin.service.destroy', ['id'=>$service->id]),'method'=>'delete', 'style'=>'display:inline-block !important']) !!}
        <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash"></i></button>
        {!! Form::close() !!}
    </td>
</tr>
@endforeach

resources/views/partials/_sidebarAdm.blade.php
<ul class="sidebar-menu">
  <li class="header">HEADER</li>
  <!-- Optionally, you can add icons to the links -->
  <li class="active"><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
  <li><a href="{{ route('admin.user.index') }}"><i class="fa fa-users"></i><span>Manage Users</span></a></li>
  <li class="treeview">
    <a href="#"><i class="fa fa-archive"></i> <span>Portfolio</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li><a href="#"><i class="fa fa-circle-o"></i> Add Portfolio</a></li>
      <li><a href="#"><i class="fa fa-circle-o"></i> List</a></li>
    </ul>
  </li>
  <li><a href="{{ route('admin.label.index') }}"><i class="fa fa-tags"></i> <span>Labels</span></a></li>
  <li>
    <a href="{{ route('admin.service.index') }}"><i class="fa fa-gears"></i> <span>Services</span></a>
  </li>
  <li><a href="{{ route('admin.teacher.index') }}"><i class="fa fa-graduation-cap"></i> <span>Teachers</span></a></li>
  <li><a href="{{ route('admin.saids.index') }}"><i class="fa fa-commenting"></i> <span>Testimonials</span></a></li>
  <li class="treeview">
    <a href="#"><i class="fa fa-gears"></i> <span>Options</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li><a href="#"><i class="fa fa-circle-o"></i> Account</a></li>
      <li><a href="#"><i class="fa fa-circle-o"></i> Page</a></li>
      <li><a href="#"><i class="fa fa-circle-o"></i> Social Media</a></li>
      <li><a href="#"><i class="fa fa-circle-o"></i> Site</a></li>
    </ul>
  </li>
</ul>

resources/views/partials/_sidebarMember.blade.php
<ul class="sidebar-menu">
  <li class="header">HEADER</li>
  <!-- Optionally, you can add icons to the links -->
  <li class="active"><a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
  <li class="treeview">
    <a href="#"><i class="fa fa-archive"></i> <span>Portfolio</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li><a href="#"><i class="fa fa-circle-o"></i> Add Portfolio</a></li>
      <li><a href="#"><i class="fa fa-circle-o"></i> List</a></li>
    </ul>
  </li>
  <li><a href="{{ route('admin.label.index') }}"><i class="fa fa-tags"></i> <span>Labels</span></a></li>
</ul>