app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as'=>'guest.index','uses'=>'GlobalController@homeIndex']);
Route::get('portfolio', ['as'=>'guest.portfolio.index','uses'=>'PortfolioController@portfolioIndex']);
Route::get('portfolio/{id}/{slug}', ['as'=>'guest.portfolio.show','uses'=>'PortfolioController@singleIndex']);
Route::get('contact', ['as'=>'guest.contact.index', 'uses'=>'ContactController@index']);
Route::post('contact', ['as'=>'guest.contact.store', 'uses'=>'ContactController@store']);
Route::get('about', ['as'=>'guest.about.index', 'uses'=>'GlobalController@about']);

Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role:admin']], function() {
	Route::get('dashboard', ['as'=>'admin.dashboard', 'uses'=>'Admin\GlobalController@dashboard']);
	Route::resource('user', 'Admin\UserController');
	Route::get('service/all', ['as'=>'admin.service.showAction', 'uses'=>'Admin\ServiceController@showAction']);
	Route::resource('teacher', 'Admin\TeacherController');
	Route::resource('service', 'Admin\ServiceController', ['except'=>['show','create']]);
	Route::resource('saids', 'Admin\SaidController');
	Route::resource('label', 'Admin\LabelController');
	Route::resource('portfolio', 'Admin\PortfolioController');


	Route::group(['prefix'=>'options'], function() {
		Route::get('user',['as'=>'admin.options.user', 'uses'=>'OptionsController@accountIndex']);
		Route::patch('user/password',['as'=>'admin.options.passSave', 'uses'=>'OptionsController@passSave']);
		Route::patch('user/info',['as'=>'admin.options.userInfo', 'uses'=>'OptionsController@userInfo']);

		// Socials
		Route::get('social', ['as'=>'admin.options.socials', 'uses'=>'OptionsController@socialIndex']);
		Route::patch('social/update', ['as'=>'admin.options.socialSave', 'uses'=>'OptionsController@socialSave']);

		// Site Options
		Route::get('site', ['as'=>'admin.options.site', 'uses'=>'OptionsController@siteIndex']);
		Route::patch('site/update', ['as'=>'admin.options.siteSave', 'uses'=>'OptionsController@siteSave']);
		Route::patch('site/verification', ['as'=>'admin.options.verification', 'uses'=>'OptionsController@verification']);

		// Page Options
		Route::get('page', ['as'=>'admin.options.page', 'uses'=>'OptionsController@pageIndex']);
		Route::patch('page/update', ['as'=>'admin.options.pageSave', 'uses'=>'OptionsController@pageSave']);
	});

});
Route::group(['prefix'=>'member', 'middleware'=>['auth', 'role:member']], function() {
  Route::resource('label', 'Admin\LabelController');
	Route::resource('portfolio', 'Admin\PortfolioController');
  Route::resource('label', 'Admin\LabelController');
});

app/Models/Teacher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $fillable = [
    	'nama', 'mapel', 'foto',
    ];

    public $timestamps = false;
}

app/Http/Controllers/Admin/TeacherController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Teacher;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['teachers'] = Teacher::all();
        return view('admin.teacher.index', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'nama' => 'required|max:100',
            'mapel' => 'required|max:100',
            'foto' => 'required|mimes:jpeg,bmp,png',
        ]);

        if($validator->fails()) {
            return redirect()->route('admin.teacher.index')->withErrors($validator);
        }

        $image = $request->foto;
        $path = public_path().'/image';
        $name = time().'_'.str_replace(' ', '_', $image->getClientOriginalName());
        $image->move($path, $name);

        Teacher::create([
            'nama' => $request->nama,
            'mapel' => $request->mapel,
            'foto' => $name,
        ]);

        \Session::flash('flash_message', [
            'subject' => 'Sukses!',
            'message' => 'Sukses menambahkan data guru',
        ]);
        return redirect()->route('admin.teacher.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['teacher'] = Teacher::find($id);
        return view('partials._modalTeacher',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = \Validator::make($request->all(), [
            'nama' => 'required|max:100',
            'mapel' => 'required|max:100',
            'foto' => 'mimes:jpeg,bmp,png',
        ]);

        if($validator->fails()) {
            return redirect()->route('admin.teacher.index')->withErrors($validator);
        }

        if(!empty($request->foto)) {
            $image = $request->foto;
            $path = public_path().'/image';
            $name = time().'_'.str_replace(' ', '_', $image->getClientOriginalName());
            $image->move($path, $name);

            Teacher::where('id', $id)->update([
                'nama' => $request->nama,
                'mapel' => $request->mapel,
                'foto' => $name,
            ]);
        } else {
            Teacher::where('id', $id)->update([
                'nama' => $request->nama,
                'mapel' => $request->mapel,
            ]);
        }
        
        \Session::flash('flash_message', [
            'subject' => 'Sukses!',
            'message' => 'Sukses menambahkan data guru',
        ]);
        return redirect()->route('admin.teacher.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Teacher::destroy($id);
        \Session::flash('flash_message', [
            'subject' => 'Sukses!',
            'message' => 'Sukses menghapus data guru',
        ]);
        return redirect()->route('admin.teacher.index');
    }
}

resources/views/admin/teacher/index.blade.php
@extends('layouts.admin', ['_pageTitle'=>'Manage Teachers', '_pageDesc'=>'Membuat, mengubah, menghapus data guru disini.'])

@section('title', 'Manage Teachers')

@section('content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Manage Teacher</h3>
            <a data-toggle="modal" href='#modal-guru' class="btn btn-primary btn-sm pull-right"><i class="fa fa-pencil"></i> Tambah</a>
        </div>
        <div class="box-body">
            @if (session()->has('flash_message.subject'))
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>{{ session()->get('flash_message.subject') }}</strong> <br>
                {{ session()->get('flash_message.message') }}
            </div>
            @elseif(count($errors) > 0)
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Error!</strong> <br>
                <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
                </ul>
            </div>
            @endif
            <div class="row">
                @if (count($teachers) === 0)
                    <center>No data found.</center>
                @endif
                @foreach ($teachers as $teacher)
                <div class="col-md-3">
                    <div class="box box-primary">
                        <div class="box-body box-profile">
                          <img class="profile-user-img img-responsive img-circle" src="{{ asset('image/'.$teacher->foto) }}" alt="User profile picture">
                          <h3 class="profile-username text-center">{{ $teacher->nama }}</h3>
                          <p class="text-muted text-center">{{ $teacher->mapel }}</p>
                          <div style="text-align: center;">
                            <a data-toggle="modal" href='#modal-edit' data-url="{{ route('admin.teacher.edit', ['id'=>$teacher->id]) }}" class="btn btn-primary"><b>Edit</b></a>
                            {!! Form::open(['url'=>route('admin.teacher.destroy', ['id'=>$teacher->id]), 'method'=>'delete', 'style'=>'display:inline-block !important', 'class'=>'form-delete']) !!}
                                <button type="submit" class="btn btn-danger">Delete</button>
                            {!! Form::close() !!}
                          </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                </div>
                @endforeach
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal-guru">
        <div class="modal-dialog">
            <div class="modal-content">
                {!! Form::open(['route'=>'admin.teacher.store', 'files'=>true]) !!}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Tambah Guru</h4>
                </div>
                <div class="modal-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <th>Nama</th>
                                    <td><input type="text" class="form-control" name="nama"></td>
                                </tr>
                                <tr>
                                    <th>Pelajaran</th>
                                    <td><input type="text" class="form-control" name="mapel"></td>
                                </tr>
                                <tr>
                                    <th>Foto</th>
                                    <td><input type="file" id="datafoto" class="form-control" name="foto"></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" id="add-guru" class="btn btn-primary">Save</button>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal-edit">
        <div class="modal-dialog">
            <div class="modal-content">
               
            </div>
        </div>
    </div>
@endsection
@section('footer-scripts')
<script>
    $(document).ready(function() {
        $('a[href="#modal-edit"]').click(function(e) {
            e.preventDefault();
            target = $(this).attr('data-url');
            $('#modal-edit .modal-content').load(target);
        });
    });
    $(document).ready(function() {
        $('.form-delete').on('submit', function() {
            konf = confirm('Apakah anda yakin  mau menghapus data ini?');
            if(konf) {
                return konf;
            } else {
                return false;
            }
        });
    });
</script>
@stop