app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as'=>'guest.index','uses'=>'GlobalController@homeIndex']);
Route::get('portfolio', ['as'=>'guest.portfolio.index','uses'=>'PortfolioController@portfolioIndex']);
Route::get('portfolio/{id}/{slug}', ['as'=>'guest.portfolio.show','uses'=>'PortfolioController@singleIndex']);
Route::get('contact', ['as'=>'guest.contact.index', 'uses'=>'ContactController@index']);
Route::post('contact', ['as'=>'guest.contact.store', 'uses'=>'ContactController@store']);
Route::get('about', ['as'=>'guest.about.index', 'uses'=>'GlobalController@about']);

Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role:admin']], function() {
	Route::get('dashboard', ['as'=>'admin.dashboard', 'uses'=>'Admin\GlobalController@dashboard']);
	Route::resource('user', 'Admin\UserController');
	Route::get('service/all', ['as'=>'admin.service.showAction', 'uses'=>'Admin\ServiceController@showAction']);
	Route::resource('teacher', 'Admin\TeacherController');
	Route::resource('service', 'Admin\ServiceController', ['except'=>['show','create']]);
	Route::resource('saids', 'Admin\SaidController');
	Route::resource('label', 'Admin\LabelController');
	Route::resource('portfolio', 'Admin\PortfolioController');


	Route::group(['prefix'=>'options'], function() {
		Route::get('user',['as'=>'admin.options.user', 'uses'=>'OptionsController@accountIndex']);
		Route::patch('user/password',['as'=>'admin.options.passSave', 'uses'=>'OptionsController@passSave']);
		Route::patch('user/info',['as'=>'admin.options.userInfo', 'uses'=>'OptionsController@userInfo']);

		// Socials
		Route::get('social', ['as'=>'admin.options.socials', 'uses'=>'OptionsController@socialIndex']);
		Route::patch('social/update', ['as'=>'admin.options.socialSave', 'uses'=>'OptionsController@socialSave']);

		// Site Options
		Route::get('site', ['as'=>'admin.options.site', 'uses'=>'OptionsController@siteIndex']);
		Route::patch('site/update', ['as'=>'admin.options.siteSave', 'uses'=>'OptionsController@siteSave']);
		Route::patch('site/verification', ['as'=>'admin.options.verification', 'uses'=>'OptionsController@verification']);

		// Page Options
		Route::get('page', ['as'=>'admin.options.page', 'uses'=>'OptionsController@pageIndex']);
		Route::patch('page/update', ['as'=>'admin.options.pageSave', 'uses'=>'OptionsController@pageSave']);
	});

});
Route::group(['prefix'=>'member', 'middleware'=>['auth', 'role:member']], function() {
  Route::resource('label', 'Admin\LabelController');
	Route::resource('portfolio', 'Admin\PortfolioController');
  Route::resource('label', 'Admin\LabelController');
});

app/Models/Portfolio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Portfolio extends Model
{
    protected $fillable = [
    	'user_id','judul','kelompok','anggota','author','thumbnail','desc','embed','durasi','slug',
    ];

    public function Labels()
    {
      return $this->belongsToMany('App\Models\Label');
    }

    public function User()
    {
      return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/Admin/PortfolioController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Label;
use App\Models\Portfolio;
use Auth;

class PortfolioController extends Controller
{
    private $_role;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
      if(Auth::user()->role_id == 2) {
        $this->_role = "member";
      } else {
        $this->_role = "admin";
      }
    }

    public function index()
    {
      if(Auth::user()->role_id == 2) {
        $data['portfolios'] = Portfolio::where('user_id', Auth::user()->id)->orderBy('id', 'desc')->paginate(10);
      } else {
        $data['portfolios'] = Portfolio::orderBy('id', 'desc')->paginate(10);
      }
      return view($this->_role.'.portfolios.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['labels'] = Label::all();
        return view($this->_role.'.portfolios.create', $data);
    }

    protected function uploadThumb($file) {
      $data = $file;
      $name = time().'_'.str_replace(' ', '_', $data->getClientOriginalName());
      $path = public_path().'/image';
      $data->move($path, $name);
      return $name;
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(), [
          'judul' => 'required',
          'desc' => 'required',
          'label' => 'required',
          'thumbnail' => 'required|mimes:jpeg,png,jpg',
        ]);

        if($validator->fails()) {
          return redirect()->route($this->_role.'.portfolio.create')->withErrors($validator)->withInput();
        }

        $label = Label::find($request->label);
        if(empty($label)) {
          \Session::flash('flash_message', [
            'level' => 'danger',
            'subject' => 'Peringatan!',
            'message' => 'Kategori yang anda masukan tidak benar',
          ]);
          return redirect()->route($this->_role.'.portfolio.create')->withErrors($validator)->withInput();
        }

        $init = Portfolio::create([
          'user_id' => Auth::user()->id,
          'judul' => $request->judul,
          'kelompok' => $request->namakelompok,
          'anggota' => $request->anggota,
          'author' => $request->namaindividu,
          'thumbnail' => $this->uploadThumb($request->thumbnail),
          'desc' => $request->desc,
          'embed' => $request->embed,
          'durasi' => $request->durasi,
          'slug' => str_slug($request->judul, '-'),
        ]);

        $init->Labels()->attach($label->id);

        \Session::flash('flash_message', [
          'message' => 'Portfolio terbaru anda sudah berhasil di publish',
        ]);
        return redirect()->route($this->_role.'.portfolio.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['portfolio'] = Portfolio::find($id);

        // check user id of portfolio
        if($data['portfolio']->user_id != Auth::user()->id) {
          \Session::flash('flash_message', [
            'message' => 'Error. Kamu tidak punya akses untuk mengedit portfolio tadi.',
          ]);
          return redirect()->route($this->_role.'.portfolio.index');
        }
        $data['labels'] = Label::where('id', '!=', $data['portfolio']->Labels()->first()->id)->get();
        return view($this->_role.'.portfolios.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $validator = \Validator::make($request->all(), [
        'judul' => 'required',
        'desc' => 'required',
        'label' => 'required',
        'thumbnail' => 'mimes:jpg,png',
      ]);

      if($validator->fails()) {
        return redirect()->route($this->_role.'.portfolio.edit',['id'=>$id])->withErrors($validator)->withInput();
      }

      $label = Label::find($request->label);
      $init = Portfolio::find($id);

      if(empty($label)) {
        \Session::flash('flash_message', [
          'level' => 'danger',
          'subject' => 'Peringatan!',
          'message' => 'Kategori yang anda masukan tidak benar',
        ]);
        return redirect()->route($this->_role.'.portfolio.edit',['id'=>$id])->withErrors($validator)->withInput();
      }

      if(empty($request->thumbnail)) {
        $init->judul = $request->judul;
        $init->kelompok = $request->namakelompok;
        $init->anggota = $request->anggota;
        $init->author = $request->namaindividu;
        $init->desc = $request->desc;
        $init->embed = $request->embed;
        $init->durasi = $request->durasi;
        $init->save();
      } else {
        $init->judul = $request->judul;
        $init->kelompok = $request->namakelompok;
        $init->anggota = $request->anggota;
        $init->author = $request->namaindividu;
        $init->desc = $request->desc;
        $init->thumbnail = $this->uploadThumb($request->thumbnail);
        $init->embed = $request->embed;
        $init->durasi = $request->durasi;
        $init->save();
      }

      $init->Labels()->updateExistingPivot($init->Labels()->first()->id, [
        'label_id' => $label->id,
      ]);

      \Session::flash('flash_message', [
        'message' => 'Portfolio anda sudah berhasil di update',
      ]);
      return redirect()->route($this->_role.'.portfolio.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $init = Portfolio::find($id);
        $init->Labels()->detach($init->Labels()->first()->id);

        if($init->user_id != Auth::user()->id) {
          \Session::flash('flash_message', [
            'message' => 'Error. Kamu tidak punya akses untuk menghapus portfolio tadi.',
          ]);
          return redirect()->route($this->_role.'.portfolio.index');
        }

        Portfolio::destroy($id);

        \Session::flash('flash_message', [
          'message' => 'Portfolio anda sudah berhasil di hapus',
        ]);
        return redirect()->route($this->_role.'.portfolio.index');
    }
}

app/Http/Controllers/PortfolioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Label;
use App\Models\Portfolio;
use App\Http\Requests;

class PortfolioController extends Controller
{
    public function singleIndex($id, $slug)
    {
      $data['portfolio'] = Portfolio::where('id', $id)->where('slug', $slug)->first();
      $data['portfolios'] = Label::where('id', $data['portfolio']->Labels()->first()->id)->first();
      return view('guest.single-post', $data);
    }

    public function portfolioIndex()
    {
      $data['labels'] = Label::take(5)->get();
      return view('guest.indexPortfolio', $data);
    }
}

resources/views/member/portfolios/edit.blade.php
@extends('layouts.admin', ['_pageTitle'=>'Edit Portfolio', '_pageDesc'=>'Menambahkan portfolio baru'])

@section('title', 'Tambah Portfolio')

@section('header-scripts')
<link rel="stylesheet" type="text/css" href="{{ asset('admin/plugins/bootstrap-select/bootstrap-select.min.css') }}">
<style type="text/css">
    .widgets:first-child {
        padding-top: 0;
    }
    .widgets {
        padding: 20px 0;
        border-bottom: 1px solid #f0f0f0;
    }
    .widgets>h3 {
        padding: 0;
        margin: 0px 0px 15px 0px;
    }
</style>
@endsection

@section('content')
    <div class="box box-warning">
        <div class="box-header with-border">
            <h3 class="box-title">Edit Portfolio</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            @if (session()->has('flash_message.subject'))
            <div class="alert alert-{{ session()->get('flash_message.level') }}">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>{{ session()->get('flash_message.subject') }}</strong> <br>
                {{ session()->get('flash_message.message') }}
            </div>
            @elseif(count($errors) > 0)
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Error!</strong> <br>
                <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
                </ul>
            </div>
            @endif

            {!! Form::open(['url'=>route('member.portfolio.update',['id'=>$portfolio->id]), 'id'=>'formmm', 'files'=>true, 'method'=>'patch']) !!}
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-10">
                            {!! Form::text('judul', $portfolio->judul, ['class'=>'form-control','placeholder'=>'Judul portfolio']) !!}
                        </div>
                        <div class="col-sm-2"><button type="submit" class="btn btn-primary btn-block">Save</button></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group">{!! Form::textarea('embed', $portfolio->embed, ['class'=>'form-control', 'id'=>'video', 'style'=>'display:none;', 'placeholder'=>'Video embed here.']) !!}</div>
                        <div class="form-group">
                            {!! Form::textarea('desc', $portfolio->desc, ['class'=>'form-control', 'id'=>'arti']) !!}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="widgets">
                            <h3>Thumbnail</h3>
                            <div class="form-group">
                              <input type="file" class="form-control" name="thumbnail">
                            </div>
                        </div>
                        <div class="widgets">
                            <h3>Template</h3>
                            <div class="form-group">
                                <select id="template" class="form-control">
                                    <option value>Pilih template (wajib)</option>
                                    <option value="1" {{ $portfolio->embed != "" ? "selected" : "" }}>Video</option>
                                    <option value="2" {{ $portfolio->embed == "" ? "selected" : "" }}>Artikel</option>
                                </select>
                            </div>
                            <div class="form-group" id="durasi" style="display: none;">
                                <label class="control-label">Durasi Video</label>
                                {!! Form::text('durasi', $portfolio->durasi, ['class'=>'form-control','placeholder'=>'Kosongkan jika tidak ada']) !!}
                            </div>
                        </div>
                        <div class="widgets">
                            <h3>Kategori</h3>
                            <div class="form-group">
                                <select class="selectpicker" name="label" data-live-search="true">
                                  @foreach ($labels as $label)
                                    <option value="{{ $portfolio->Labels()->first()->id }}" selected>{{ $portfolio->Labels()->first()->label }}</option>
                                    <option value="{{ $label->id }}">{{ $label->label }}</option>
                                  @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="widgets">
                            <h3>Pengerjaan</h3>
                            <div class="form-group">
                                <select id="kelompok" class="form-control">
                                    <option value>Select metode -</option>
                                    <option value="1" {{ $portfolio->kelompok != "" ? "selected" : "" }}>Berkelompok</option>
                                    <option value="2" {{ $portfolio->kelompok == "" ? "selected" : "" }}>Individu</option>
                                </select>
                            </div>
                            <div class="form-group" id="selkelompok" style="display: none;">
                                {!! Form::text('namakelompok', $portfolio->kelompok, ['class'=>'form-control', 'placeholder'=>'Nama kelompok']) !!}
                            </div>
                            <div class="form-group" id="anggota" style="display: none;">
                                {!! Form::text('anggota', $portfolio->anggota, ['class'=>'form-control', 'placeholder'=>'Anggota']) !!}
                                <span class="help-block">Gunakan ';' untuk pemisah anggota. Misalkan jhon;doe;samantha</span>
                            </div>
                            <div class="form-group" id="individu" style="display: none;">
                                {!! Form::text('namaindividu', $portfolio->author, ['class'=>'form-control', 'placeholder'=>'Nama creator']) !!}
                            </div>
                        </div>
                    </div>
                </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

@section('footer-scripts')
<script src="{{ asset('admin/plugins/bootstrap-select/bootstrap-select.min.js') }}"></script>
<script src="{{ asset('admin/plugins/tinymce/tinymce.min.js') }}"></script>
<script>
    tinymce.init({
      selector: 'textarea#arti',
      height: 400,
      plugins: [
        'advlist autolink lists link image charmap print preview anchor',
        'searchreplace visualblocks code fullscreen',
        'insertdatetime media table contextmenu paste code'
      ],
      toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
    });

    $(document).ready(function() {
        $('.selectpicker').selectpicker({
          style: 'btn-default',
          size: 10,
          width: '100%',
        });
    });

    $(document).ready(function() {
        method = $('#kelompok');
        if(method.val() == "1") {
            $('#selkelompok').slideDown();
            $('#anggota').slideDown();
            $('#individu').slideUp();
            $('input[name="namaindividu"]').val('');
        } else if (method.val() == "2") {
            $('#selkelompok').slideUp();
            $('#anggota').slideUp();
            $('input[name="namakelompok"]').val('');
            $('input[name="anggota"]').val('');
            $('#individu').slideDown();
        }
        method.on('change', function(e) {
            e.preventDefault();
            if(method.val() == "1") {
                $('#selkelompok').slideDown();
                $('#anggota').slideDown();
                $('#individu').slideUp();
                $('input[name="namaindividu"]').val('');
            } else if (method.val() == "2") {
                $('#selkelompok').slideUp();
                $('#anggota').slideUp();
                $('input[name="namakelompok"]').val('');
                $('input[name="anggota"]').val('');
                $('#individu').slideDown();
            }
        });
    });
    $(document).ready(function() {
        element = $('#template');
        if(element.val() == "1") {
            $('#video').slideDown();
            $('#durasi').slideDown();
        } else if (element.val() == "2") {
            $('#video').slideUp();
            $('#durasi').slideUp();
            $('input[name="durasi"]').val('');
            $('textarea[name="embed"]').val('');
        }
        element.on('change', function() {
            if(element.val() == "1") {
                $('#video').slideDown();
                $('#durasi').slideDown();
            } else if (element.val() == "2") {
                $('#video').slideUp();
                $('#durasi').slideUp();
                $('input[name="durasi"]').val('');
                $('textarea[name="embed"]').val('');
            }
        });
    });
</script>
@stop;

resources/views/member/portfolios/index.blade.php
@extends('layouts.admin', ['_pageTitle'=>'Portfolio', '_pageDesc'=>'Daftar portfolio yang telah di publish,'])

@section('title', 'Manage Portfolio')

@section('content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Manage Portfolio</h3>
            <a href='{!! route('member.portfolio.create') !!}' class="btn btn-primary btn-sm pull-right"><i class="fa fa-pencil"></i> Baru</a>
        </div>
        <div class="box-body">
            @if (session()->has('flash_message.message'))
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Sukses!</strong> <br>
                {{ session()->get('flash_message.message') }}
            </div>
            @elseif(count($errors) > 0)
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Error!</strong> <br>
                <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
                </ul>
            </div>
            @endif

            @if (count($portfolios) < 1)
            <span>Tidak ada data.</span>
            @else
            <div class="table-responsive">
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                          <th>No</th>
                          <th>Judul</th>
                          <th>Mode</th>
                          <th>Kategori</th>
                          <th>Pada</th>
                          <th>Oleh</th>
                          <th>Action</th>
                        </tr>
                    </thead>
                    <tbody id="result-faker">
                        <?php $i = 1+($portfolios->perPage() * 0)+$portfolios->currentPage()-1; ?>
                        @foreach ($portfolios as $portfolio)
                          <tr>
                            <td>{{ $i++ }}</td>
                            <td>{{ $portfolio->judul }}</td>
                            <td><span class="label label-primary">{{ $portfolio->kelompok == "" ? 'Individu' : 'Kelompok' }}</span></td>
                            <td>{{ $portfolio->Labels()->first()->label }}</td>
                            <td>{{ date("d M Y", strtotime($portfolio->created_at)) }}</td>
                            <td>{{ $portfolio->User->name }}</td>
                            <td>
                              <a href="{!! route('member.portfolio.edit', ['id'=>$portfolio->id]) !!}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
                              {!! Form::open(['url'=>route('member.portfolio.destroy',['id'=>$portfolio->id]), 'method'=>'delete','class'=>'form-delete', 'style'=>'display:inline-block !important;']) !!}
                                <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                              {!! Form::close() !!}
                            </td>
                          </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            @endif
            {!! $portfolios->render() !!}
        </div>
    </div>
@endsection
@section('footer-scripts')
<script type="text/javascript">
$(document).ready(function() {
    $('.form-delete').on('submit', function() {
        konf = confirm('Apakah anda yakin  mau menghapus data ini?');
        if(konf) {
            return konf;
        } else {
            return false;
        }
    });
});
</script>
@stop