app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as'=>'guest.index','uses'=>'GlobalController@homeIndex']);
Route::get('portfolio', ['as'=>'guest.portfolio.index','uses'=>'PortfolioController@portfolioIndex']);
Route::get('portfolio/{id}/{slug}', ['as'=>'guest.portfolio.show','uses'=>'PortfolioController@singleIndex']);
Route::get('contact', ['as'=>'guest.contact.index', 'uses'=>'ContactController@index']);
Route::post('contact', ['as'=>'guest.contact.store', 'uses'=>'ContactController@store']);
Route::get('about', ['as'=>'guest.about.index', 'uses'=>'GlobalController@about']);

Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role:admin']], function() {
	Route::get('dashboard', ['as'=>'admin.dashboard', 'uses'=>'Admin\GlobalController@dashboard']);
	Route::resource('user', 'Admin\UserController');
	Route::get('service/all', ['as'=>'admin.service.showAction', 'uses'=>'Admin\ServiceController@showAction']);
	Route::resource('teacher', 'Admin\TeacherController');
	Route::resource('service', 'Admin\ServiceController', ['except'=>['show','create']]);
	Route::resource('saids', 'Admin\SaidController');
	Route::resource('label', 'Admin\LabelController');
	Route::resource('portfolio', 'Admin\PortfolioController');


	Route::group(['prefix'=>'options'], function() {
		Route::get('user',['as'=>'admin.options.user', 'uses'=>'OptionsController@accountIndex']);
		Route::patch('user/password',['as'=>'admin.options.passSave', 'uses'=>'OptionsController@passSave']);
		Route::patch('user/info',['as'=>'admin.options.userInfo', 'uses'=>'OptionsController@userInfo']);

		// Socials
		Route::get('social', ['as'=>'admin.options.socials', 'uses'=>'OptionsController@socialIndex']);
		Route::patch('social/update', ['as'=>'admin.options.socialSave', 'uses'=>'OptionsController@socialSave']);

		// Site Options
		Route::get('site', ['as'=>'admin.options.site', 'uses'=>'OptionsController@siteIndex']);
		Route::patch('site/update', ['as'=>'admin.options.siteSave', 'uses'=>'OptionsController@siteSave']);
		Route::patch('site/verification', ['as'=>'admin.options.verification', 'uses'=>'OptionsController@verification']);

		// Page Options
		Route::get('page', ['as'=>'admin.options.page', 'uses'=>'OptionsController@pageIndex']);
		Route::patch('page/update', ['as'=>'admin.options.pageSave', 'uses'=>'OptionsController@pageSave']);
	});

});
Route::group(['prefix'=>'member', 'middleware'=>['auth', 'role:member']], function() {
  Route::resource('label', 'Admin\LabelController');
	Route::resource('portfolio', 'Admin\PortfolioController');
  Route::resource('label', 'Admin\LabelController');
});

app/Models/Label.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Label extends Model
{
    protected $fillable = [
    	'label',
    ];

    public $timestamps = false;

    public function Portfolios()
    {
      return $this->belongsToMany('App\Models\Portfolio');
    }
}

app/Http/Controllers/Admin/LabelController.php
<?php

namespace App\Http\Controllers\Admin;

use Request;
use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Label;
use Auth;

class LabelController extends Controller
{
    private $_role;

    public function __construct()
    {
      if(Auth::user()->role_id == 2) {
        $this->_role = "member";
      } else {
        $this->_role = "admin";
      }
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['labels'] = Label::paginate(8);
        return view('admin.label.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['labels'] = Label::paginate(8);
        return view('partials._labelLists', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        if(Request::ajax()) {
            $validator = \Validator::make(Request::all(), [
                'label' => 'required|min:3|max:255|unique:labels',
            ]);

            if($validator->fails()) {
                return response()->json([
                    'success' => false,
                    'message' => $validator->errors()->toArray(),
                ]);
            }

            Label::create(Request::all());

            return response()->json([
                'success' => true,
                'message' => 'Selamat, label baru telah berhasil di tambahkan.',
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['label'] = Label::find($id);
        return view('partials._modalLabel', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($id)
    {
        if(Request::ajax()) {
            $data = Request::all();
            $validator = \Validator::make($data, [
                'label' => 'required|min:3|max:255|unique:labels',
            ]);

            if($validator->fails()) {
                return response()->json([
                    'success' => false,
                    'message' => $validator->errors()->toArray(),
                ]);
            }

            $init = Label::find($id);
            $init->label = $data['label'];
            $init->save();

            return response()->json([
                'success' => true,
                'message' => 'Selamat, label baru telah berhasil di tambahkan.',
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $init = Label::find($id);
        if($init->Portfolios()->count() > 0) {
          return response()->json([
              'success' => false,
              'message' => 'Gagal, label ini masih mempunyai portfolio yang terkait, hapus terlebih dahulu portfolio tersebut',
          ]);
        }

        Label::destroy($id);
        return response()->json([
            'success' => true,
            'message' => 'Selamat, label telah berhasil di hapus.',
        ]);
    }
}

resources/views/member/label/index.blade.php
@extends('layouts.admin', ['_pageTitle'=>'Manage Labels', '_pageDesc'=>'Membuat, mengubah, menghapus data label disini.'])

@section('title', 'Manage Labels')

@section('content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Manage Labels</h3>
        </div>
        <div class="box-body">
            <form action="" method="POST" class="form-horizontal">
                    <div class="form-group">
                        <div class="col-sm-10">
                            <input type="text" placeholder="Add new label..." name="label" class="form-control">
                        </div>
                        <div class="col-sm-2"><button id="submit" type="button" class="btn btn-block btn-primary">Submit</button></div>
                    </div>
            </form>
            @if (session()->has('flash_message.message'))
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Sukses!</strong> <br>
                {{ session()->get('flash_message.message') }}
            </div>
            @endif
            <div id="info" style="display: none;">
                <div class="alert alert-warning">
                    <strong>Error!</strong> <br>
                    <ul></ul>
                </div>
            </div>
            <div id="success" style="display: none;">
                <div class="alert alert-success">
                    <button type="button" data-close="close" class="close">&times;</button>
                    <strong>Sukses!</strong> <br>
                    <p class="isi"></p>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Label</th>
                            <th>Jumlah Post</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody id="faker">
                        @if (count($labels) < 1)
                            <p>Belum ada data.</p>
                        @endif
                        <?php $i = 1+($labels->perPage() * 0)+$labels->currentPage()-1; ?>
                        @foreach ($labels as $label)
                        <tr>
                            <td>{{ $i++ }}</td>
                            <td>{{ $label->label }}</td>
                            <td></td>
                            <td>
                                <a href="#modal-edit" data-toggle="modal" data-url="{{ route('member.label.edit', ['id'=>$label->id]) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
                                <button data-delete="delete" data-url="{{ route('admin.label.destroy', ['id'=>$label->id]) }}" class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash"></i></button>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            {!! $labels->render() !!}
        </div>
    </div>
    <div class="modal fade" id="modal-edit">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>
@endsection
@section('footer-scripts')
<script>
    $('button[data-close="close"]').on('click', function(e) {
        e.preventDefault();
        $('#success').slideUp();
        $('#success .isi').text('');
    });

    $(document).ready(function() {
        $('a[href="#modal-edit"]').click(function(e) {
            e.preventDefault();
            $('#modal-edit .modal-content').append('<center><img src="dist/img/ajax-loader.gif" style="padding:20px auto"></center>');
            data = $(this).attr('data-url');
            $('#modal-edit .modal-content').load(data);
        });
    });

    $(document).ready(function() {
        info = $('#info');
        sukses = $('#success');

        $('#submit').on('click', function(e) {
            e.preventDefault();
            $.ajaxSetup({
                headers: {'X-CSRF-Token' : $('meta[name="csrf-token"]').attr('content') }
            });

            $.ajax({
                url : 'label',
                type : 'post',
                data : {
                    'label' : $('input[name="label"]').val(),
                },
                success : function(data) {
                    if(!data.success) {
                        obj = info.find('ul').empty();
                        $.each(data.message, function(index, message) {
                            obj.append('<li>'+message+'</li>');
                        });
                        info.slideDown();
                    } else {
                        sukses.find('.isi').text(' ');
                        obj = sukses.find('.isi').append(data.message);
                        sukses.slideDown();

                        $('#faker').load('label/create');
                    }
                }
            });
        });

        $('button[data-delete="delete"]').on('click', function(e) {
            e.preventDefault();

            konf = confirm('Apakah anda yakin  mau menghapus data ini?');
            if(!konf) {
                return false;
            }

            data = $(this).attr('data-url');

            $.ajaxSetup({
                headers: {'X-CSRF-Token' : $('meta[name="csrf-token"]').attr('content') }
            });

            $.ajax({
                url : data,
                type : 'delete',
                success: function(data) {
                    obj = sukses.find('.isi').append(data.message);
                    sukses.slideDown();
                    $('#faker').load('label/create');
                }
            });
        });
    });
</script>
@stop